//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package firehose

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Record) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.CreatedAt (typegen.DagJsonTime) (struct)
	if len("created_at") > 8192 {
		return fmt.Errorf("string in field \"created_at\" was too long")
	}
	if err := jw.WriteString(string("created_at")); err != nil {
		return fmt.Errorf("writing string for field \"created_at\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.CreatedAt.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.CreatedAt: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Path ([][]uint8) (slice)
	if len("path") > 8192 {
		return fmt.Errorf("string in field \"path\" was too long")
	}
	if err := jw.WriteString(string("path")); err != nil {
		return fmt.Errorf("writing string for field \"path\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Path) > 8192 {
		return fmt.Errorf("slice value in field t.Path was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Path: %w", err)
	}
	for i, v := range t.Path {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Path: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("writing bytes for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Path: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Revocation ([]uint8) (slice)
	if len("revocation") > 8192 {
		return fmt.Errorf("string in field \"revocation\" was too long")
	}
	if err := jw.WriteString(string("revocation")); err != nil {
		return fmt.Errorf("writing string for field \"revocation\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Revocation) > 2097152 {
		return fmt.Errorf("byte array in field t.Revocation was too long")
	}

	if err := jw.WriteBytes(t.Revocation); err != nil {
		return fmt.Errorf("writing bytes for field t.Revocation: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Record) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Record{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Record: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Record: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Record: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Record: string too large")
				}
				return fmt.Errorf("reading string for field Record: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Record: %w", err)
			}
			switch name {

			// t.CreatedAt (typegen.DagJsonTime) (struct)
			case "created_at":

				if err := t.CreatedAt.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.CreatedAt: %w", err)
				}

				// t.Path ([][]uint8) (slice)
			case "path":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Path: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Path: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Path: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading bytes for field item[0]: byte array too large")
									}
									return fmt.Errorf("reading bytes for field item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Path = append(t.Path, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Path: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Path: slice too large")
							}
						}
					}

				}

				// t.Revocation ([]uint8) (slice)
			case "revocation":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Revocation: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Revocation: %w", err)
					}
					if len(bval) > 0 {
						t.Revocation = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Record: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Record: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Record")
			}
		}
	}

	return nil
}
